version: "3.4"

services:
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - backend
    ports:
      - 5432:5432

  main:
    build: .
    environment:
      DATABASE_HOST: database
      DATABASE_USER: postgres
      DATABASE_DBNAME: postgres
      RUST_LOG: info
    networks:
      - backend
    ports:
      - 3000:3000
    depends_on:
      - database

networks:
  backend: {}
