version: 2

workflows:
  version: 2
  workflow:
    jobs:
      # - test-client
      - lint-server
      - test-server
      - build-image:
          requires:
            # - test-client
            - test-server
            - lint-server
          filters:
            tags:
              ignore: /.*/
      - push-image:
          requires:
            - test-server
            - lint-server
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  # test-client:
  #   docker:
  #     - image: docker:stable
  #   steps:
  #     - run: apk add --no-cache curl
  #     - run: mkdir -p ~/.docker/cli-plugins
  #     - run: curl --output ~/.docker/cli-plugins/docker-buildx --location --retry 3 https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64
  #     - run: chmod a+x ~/.docker/cli-plugins/docker-buildx
  #     - run: docker buildx install
  #     - checkout
  #     - setup_remote_docker
  #     - run: docker buildx build --tag jolimail-test-client --target client-base --load .
  #     - run: docker run -e CI=true jolimail-test-client npm test

  lint-server:
    docker:
      - image: rust:1-slim-buster
    steps:
      - run: rustup component add rustfmt
      - checkout
      - run:
          command: cargo fmt -- --check src/{**/,}*.rs
          working_directory: ~/project/server

  test-server:
    docker:
      - image: jdrouet/rust-nightly:buster-slim-dev
      - image: postgres:12-alpine
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          command: cargo test
          working_directory: ~/project/server
          environment:
            DATABASE_HOST: localhost
            DATABASE_USER: postgres
            DATABASE_DBNAME: postgres
            MIGRATION_PATH: migrations
            TEST_MIGRATION_PATH: migrations

  build-image:
    docker:
      - image: jdrouet/docker-with-buildx:stable
    steps:
      - run: docker buildx install
      - checkout
      - setup_remote_docker
      - run: docker buildx build --tag jdrouet/jolimail:$CIRCLE_BRANCH .

  push-image:
    docker:
      - image: jdrouet/docker-with-buildx:stable
    steps:
      - run: docker buildx install
      - checkout
      - setup_remote_docker
      - run: docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: docker buildx build --push --file dockerfiles/common.Dockerfile --tag jdrouet/jolimail:latest --tag jdrouet/jolimail:$CIRCLE_TAG --platform linux/amd64,linux/i386,linux/arm64,linux/arm/v7 --label org.label-schema.version=$CIRCLE_TAG --label org.label-schema.vcs-ref=$CIRCLE_SHA1 .
